basePath: /
consumes:
- application/json
info:
  description: Documentation for Product API.
  title: Products API.
  version: 0.0.1
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productResponse'
      tags:
      - products
produces:
- application/json
schemes:
- http
swagger: "2.0"
