basePath: /
consumes:
- application/json
info:
  description: Documentation for Product API.
  title: Products API.
  version: 0.0.1
paths:
  /categories/:
    get:
      description: Returns a list of products
      operationId: listCategories
      responses:
        "200":
          $ref: '#/responses/categoryResponse'
      tags:
      - categories
    post:
      description: Adds a new product
      operationId: Category
      responses:
        "201":
          $ref: '#/responses/http.StatusCreated'
      tags:
      - categories
  /categories/{id}:
    delete:
      description: Deletes a product
      operationId: Category
      tags:
      - categories
    put:
      description: Updates an existing product
      operationId: Category
      tags:
      - categories
  /products/:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productResponse'
      tags:
      - products
    post:
      description: Adds a new product
      operationId: Product
      responses:
        "201":
          $ref: '#/responses/http.StatusCreated'
      tags:
      - products
  /products/{id}:
    delete:
      description: Deletes a product
      operationId: Product
      tags:
      - products
    put:
      description: Updates an existing product
      operationId: Product
      tags:
      - products
produces:
- application/json
schemes:
- http
swagger: "2.0"
